export enum BusinessErrorCode {
    USER_NOT_FOUND = "USER_NOT_FOUND",
    EMAIL_FORMAT_NOT_VALID = "EMAIL_FORMAT_NOT_VALID",
    USERNAME_EMPTY = "USERNAME_EMPTY",
    PASSWORD_FORMAT_NOT_VALID = "PASSWORD_FORMAT_NOT_VALID",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
}
